###
###
# Ansible setup new clients
#
# Changelogs:
# - v1: 23/05/2021 - initial release
# - v2: 29/08/2021 - removed uid
# - v3: 15/09/2024 - updated tasks name, dropped CentOS
###
###
# Pre-requisite:
# - Create an inventory file with the following contents:
#   [all]
#   <ip address of client>
#
# Usage: ansible-playbook ansible-setup-clients.yml --extra-vars "host=<ip address> remote_ansible_user=<ansible user>" -i <path to ansible host file> -u <existing remote user> -k -K
---
- name: Ansible setup new clients
  hosts: all
  become: yes
  become_user: root
  
  # Default variables
  vars:
    remote_ansible_user: "ansibleusr"
    ssh_pri_key: "/root/.ssh/id_rsa"
    ssh_pub_key: "/root/.ssh/id_rsa.pub"
    ssh_port: 22


  tasks:
  - name: Create Ansible Remote User {{ remote_ansible_user }} for Ubuntu or Debian
    ansible.builtin.user:
      name: "{{ remote_ansible_user }}"
      comment: "Ansible Automation"
      group: sudo
      password: '*'
      expires: -1
      home: /home/{{ remote_ansible_user }}
      state: present
    when: ansible_distribution=="Ubuntu" or ansible_distribution=="Debian"

  - name: Create Ansible Remote User {{ remote_ansible_user }} for Red Hat or Rocky Linux
    ansible.builtin.user:
      name: "{{ remote_ansible_user }}"
      comment: "Ansible Automation"
      group: wheel
      password: '*'
      expires: -1
      home: /home/{{ remote_ansible_user }}
      state: present
    when: ansible_distribution=="RedHat" or ansible_distribution=="Rocky"

  - name: Set sudo for {{ remote_ansible_user }}
    ansible.builtin.copy:
      dest: /etc/sudoers.d/{{ remote_ansible_user }}
      content: '{{ remote_ansible_user }} ALL=(ALL) NOPASSWD: ALL'
      owner: root
      group: root
      mode: '0440'
      validate: /sbin/visudo -csf %s

  - name: Set authorized key for {{ remote_ansible_user }}
    ansible.posix.authorized_key:
      user: "{{ remote_ansible_user }}"
      state: present
      key: "{{ lookup('file', '{{ ssh_pub_key }}') }}"

  - name: Test SSH Public Key authentication for {{ remote_ansible_user }}
    ansible.builtin.shell: ssh -i {{ ssh_pri_key }} -p {{ ssh_port }} {{ remote_ansible_user }}@{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}
    args:
      executable: /bin/bash
    delegate_to: localhost