###
###
# Detect OS Family and Distribution
#
# Changelogs:
# - v1.0: 23/05/2021 - initial release
# - v1.1: 26/05/2021 - added architecture
# - v1.2: 15/09/2024 - updated tasks name
###
###
# Usage: ansible-playbook detect-family-distribution.yml [-i <path to ansible host file>] [-u <existing remote user> -k -K]
---
- name: Detect OS Family and Distribution
  hosts: all
  become: no


  tasks:
  - name: OS Family
    ansible.builtin.debug: msg="{{ ansible_os_family }}"

  - name: Distribution
    ansible.builtin.debug: msg="{{ ansible_distribution }}"

  - name: Distribution Release
    ansible.builtin.debug: msg="{{ ansible_distribution_release }}"

  - name: Distribution version
    ansible.builtin.debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    ansible.builtin.debug: msg="{{ ansible_distribution_major_version }}"

  - name: Architecture
    ansible.builtin.debug: msg="{{ ansible_architecture }}"