###
###
# Detect OS Family and Distribution
#
# Changelogs:
# - v1.0: 23/05/2021 - initial release
# - v1.1: 26/05/2021 - added architecture
###
###
---
- name: Detect OS Family and Distribution
  hosts: all
  become: no


  tasks:
  - name: OS Family
    debug: msg="{{ ansible_os_family }}"

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution Release
    debug: msg="{{ ansible_distribution_release }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"

  - name: Architecture
    debug: msg="{{ ansible_architecture }}"
